# -*- coding: utf-8 -*-
"""file_processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RLX9Vx9S35lmUfmFZMwmJnhUXVnl2lAq
"""

def modify_fasta_headers(input_file, output_file):
  with open(input_file,'r') as f:
    lines = f.readlines()

  modified_lines = []
  for line in lines:
    if line.startswith('>'):
      modified_lines.append("<|endoftext|>")
    else:
      modified_lines.append(line)

  with open(output_file, 'w') as f:
    f.writelines(modified_lines)