# -*- coding: utf-8 -*-
"""Processing_fasta_files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RLX9Vx9S35lmUfmFZMwmJnhUXVnl2lAq
"""

import os

input_folder = os.path.join(shared_path, 'fulldataset')
output_folder = os.path.join(shared_path, 'modifiedfasta')
for fasta_file in files_folder:
  input_file = input_folder + '/' + fasta_file
  output_file = output_folder + '/' + fasta_file
  modify_fasta_headers(input_file, output_file)